FROM ubuntu
RUN apt-get update
RUN apt-get install -y apache2
RUN apt-get install -y apache2-utils
RUN apt-get clean
COPY ./build/app/probe_cli /bin/probe_cli
RUN probe_cli --version
CMD ["apache2ctl", "-D", "FOREGROUND"]
HEALTHCHECK --retries=1 --timeout=10s --interval=3s CMD probe_cli --port=80 localhost
